networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - back
      - front
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  front:
    build:
      context: ./frontend
    networks:
      - dev

  back:
    build:
      context: ./backend
    networks:
      - dev
